---
certmanager:
  namespace: "cert-manager"
  release_name_prefix: "h3xinfra-certmanager"
  chart_version: "v1.19.2"

  cluster_issuer_email: "letsencrypt@example.com"
  cluster_issuer_dns: 
  - 'example.com'
  - '*.example.com'